name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  deploy-win:
    runs-on: windows-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Get Version from Project File
       id: get-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 9.0.x
     - name: Publish Application
       run: dotnet publish MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj -c Release -o publish -r win-x64
     - name: Create Velopack Release
       run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN  }}
          vpk pack -u MouthKing --packTitle MouthKing --icon logo.ico -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "MouthKing ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN  }}
  deploy-linux:
    runs-on: linux-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Get Version from Project File
       id: get-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 9.0.x
     - name: Publish Application
       run: dotnet publish MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj -c Release -o publish -r linux-x64
     - name: Create Velopack Release
       run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN  }}
          vpk pack -u MouthKing --packTitle MouthKing --icon logo.ico -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "MouthKing ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN  }}
  deploy-macos-intel:
    runs-on: macos-13
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Get Version from Project File
       id: get-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 9.0.x
     - name: Publish Application
       run: dotnet publish MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj -c Release -o publish -r osx-x64
     - name: Create Velopack Release
       run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN  }}
          vpk pack -u MouthKing --packTitle MouthKing --icon logo.icns -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "MouthKing ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN  }}
  deploy-macos-m1:
    runs-on: macos-14
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Get Version from Project File
       id: get-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 9.0.x
     - name: Publish Application
       run: dotnet publish MouthKing.UI.Desktop/MouthKing.UI.Desktop.csproj -c Release -o publish -r osx-arm64
     - name: Create Velopack Release
       run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN  }}
          vpk pack -u MouthKing --packTitle MouthKing --icon logo.icns -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "MouthKing ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN  }}